### ISSUE TITLE
itsdangerous should be included in requirements.txt

### ISSUE THREAD

**Issue by skewty** [pyx/sanic-cookiesession#2]
I believe itsdangerous should be included in requirements.txt.  Is there a reason why it isn't in there?

**Comment by pyx** [comment]
It's a trick to avoid duplicate code.

`itsdangerous` is included here:

https://github.com/pyx/sanic-cookiesession/blob/61368c8a4d9bbd0eb9f0337b3535e93c1210066d/setup.py#L39

With only `-e .` listed in `requirements.txt`, it's technically doing `python setup.py -e .` when you `pip install -r requirements.txt`, whether it is a good practice[1] is debatable, though.

[1]: some people believe that `requirements.txt` should be used to pin versions of dependencies.
